// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw0CZlQC_TNZ_BHZmFo_3KHRCuiLyuxmw',
    appId: '1:341740086472:web:0448324b143ac143c2f1fd',
    messagingSenderId: '341740086472',
    projectId: 'sea-innovators',
    authDomain: 'sea-innovators.firebaseapp.com',
    storageBucket: 'sea-innovators.appspot.com',
    measurementId: 'G-262HFR6KB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7eOGqJ96X-xfZ9IxqOx1g7VXnkknd8lk',
    appId: '1:341740086472:android:0c2932d265c6c422c2f1fd',
    messagingSenderId: '341740086472',
    projectId: 'sea-innovators',
    storageBucket: 'sea-innovators.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUvWOvHWg7aXgv3jPd2aOBPqGQkIB2_gw',
    appId: '1:341740086472:ios:7a7f1a736296f94bc2f1fd',
    messagingSenderId: '341740086472',
    projectId: 'sea-innovators',
    storageBucket: 'sea-innovators.appspot.com',
    iosBundleId: 'com.example.fishersERegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUvWOvHWg7aXgv3jPd2aOBPqGQkIB2_gw',
    appId: '1:341740086472:ios:7a7f1a736296f94bc2f1fd',
    messagingSenderId: '341740086472',
    projectId: 'sea-innovators',
    storageBucket: 'sea-innovators.appspot.com',
    iosBundleId: 'com.example.fishersERegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw0CZlQC_TNZ_BHZmFo_3KHRCuiLyuxmw',
    appId: '1:341740086472:web:9e33ccac38890167c2f1fd',
    messagingSenderId: '341740086472',
    projectId: 'sea-innovators',
    authDomain: 'sea-innovators.firebaseapp.com',
    storageBucket: 'sea-innovators.appspot.com',
    measurementId: 'G-D8MS9PGLS3',
  );
}
